<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>EveOPreview</RootNamespace>
    <AssemblyName>EVE-O Preview</AssemblyName>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <UseWindowsForms>true</UseWindowsForms>
	<UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Configurations>Build;Debug;Release</Configurations>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <StartupObject>EveOPreview.Program</StartupObject>
    <ManifestCertificateThumbprint>4B29FD125BFAD24FF900FC81CCE0B0AD37464FDB</ManifestCertificateThumbprint>
    <ManifestKeyFile>preview toy_TemporaryKey.pfx</ManifestKeyFile>
    <GenerateManifests>false</GenerateManifests>
    <SignManifests>false</SignManifests>
    <TargetZone>LocalIntranet</TargetZone>
    <AssemblyOriginatorKeyFile />
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <FileVersion>10.0.0.23</FileVersion>
    <AssemblyVersion>10.0.0.23</AssemblyVersion>
    <Version>10.0.0.23</Version>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\bin</OutputPath>
    <UseVSHostingProcess>false</UseVSHostingProcess>
    <RunCodeAnalysis>false</RunCodeAnalysis>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\..\bin</OutputPath>
    <UseVSHostingProcess>false</UseVSHostingProcess>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Build|AnyCPU'">
    <OutputPath>bin\Build\</OutputPath>
    <Optimize>true</Optimize>
    <UseVSHostingProcess>false</UseVSHostingProcess>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Autofac" Version="9.1.0" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="MediatR.Extensions.Autofac.DependencyInjection" Version="14.0.0" />
    <PackageReference Include="MouseKeyHook" Version="5.7.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="View\CustomControl\DarkModeContextMenuStrip.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="View\CustomControl\OutlinedLabel.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="View\Implementation\StaticThumbnailImage.cs">
      <SubType>Component</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="app.manifest" />
    <Content Include="LICENSE.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <None Update="EveoPreviewRootCA.crt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Launch Eve-O Preview with Verbose Logging.cmd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Content Include="icon.ico" />
  </ItemGroup>
  <ItemGroup Label="Compile items now included by globbing that were not in the original project file">
    <Compile Remove="AboutBox.Designer.cs" />
    <Compile Remove="AboutBox.cs" />
  </ItemGroup>
  <ItemGroup Label="EmbeddedResource items now included by globbing that were not in the original project file">
    <EmbeddedResource Remove="AboutBox.resx" />
  </ItemGroup>
</Project>